services:
  db:
    container_name: hukt-db
    image: postgres:16.2-alpine3.19
    restart: always
    env_file:
      # POSTGRES_USER
      # POSTGRES_PASSWORD
      # POSTGRES_DB
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - postgres_net

volumes:
  db:
    driver: local

networks:
  postgres_net:
    driver: bridge
