services:
  postgres:
    container_name: development-database
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - dev_db:/var/lib/postgresql/data
    networks:
      - dev_network
    
volumes:
  dev_db:
    driver: local

networks:
  dev_network: 
    driver: bridge